name: megahack
description: Hackathon.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rflutter_alert: ^1.0.3
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  panorama: ^0.0.2
  flutter_slidable: ^0.5.4
  splashscreen: ^1.2.0
  audioplayers: ^0.15.1
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/produto.wav
    - assets/images/
    - assets/360images/
    - assets/products/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
